In [2]:
import pandas as pd

In [3]:
routes = pd.read_csv(
    "../data/routes.csv"
)

routes.head()

,route_id,departure_airport,arrival_airport,departure_country,arrival_country,departure_region,arrival_region,is_international,distance_km,avg_flight_time_h,annual_flights_2023,annual_passengers_2023,load_factor_pct,avg_aircraft_age_years,risk_index,incidents_per_mn_flights,route_type
0,RT00001,HKJK,URSS,Kenya,Russia,Africa,Europe,1,959,1.1,565,73890,83.0,7.7,0.100,0.1598,Short-haul
1,RT00002,CYVR,UUEE,Canada,Russia,NorthAmerica,Europe,1,1570,1.8,5362,662654,77.9,6.9,0.122,0.2137,Short-haul
2,RT00003,VVTS,SCVD,Vietnam,Chile,AsiaPacific,LatinAmerica,1,6649,7.8,1010,158372,80.9,1.0,0.271,0.1816,Long-haul
3,RT00004,SBSV,HTKJ,Brazil,Tanzania,LatinAmerica,Africa,1,6419,7.6,719,119049,88.9,7.8,0.117,0.5618,Long-haul
4,RT00005,HTKJ,KJFK,Tanzania,USA,Africa,NorthAmerica,1,203,0.2,1321,254151,86.0,9.6,0.204,0.2298,Short-haul

In [4]:
routes.sort_values(
    "risk_index",
    ascending=False
).head(20)

,route_id,departure_airport,arrival_airport,departure_country,arrival_country,departure_region,arrival_region,is_international,distance_km,avg_flight_time_h,annual_flights_2023,annual_passengers_2023,load_factor_pct,avg_aircraft_age_years,risk_index,incidents_per_mn_flights,route_type
886,RT00887,VVDN,VOMM,Vietnam,India,AsiaPacific,AsiaPacific,1,1936,2.3,5202,812464,91.3,10.4,2.854,0.5267,Short-haul
4974,RT04975,CYYC,KATL,Canada,USA,NorthAmerica,NorthAmerica,1,1942,2.3,6057,759882,84.7,11.0,2.851,0.1108,Short-haul
1683,RT01684,KORD,VNKT,USA,Nepal,NorthAmerica,SouthAsia,1,1039,1.2,917,107469,76.2,7.1,2.810,0.1219,Short-haul
966,RT00967,LFLL,FNHU,France,Angola,Europe,Africa,1,1105,1.3,6094,876915,79.1,15.2,2.546,0.3745,Short-haul
3414,RT03415,VIDP,SKCL,India,Colombia,AsiaPacific,LatinAmerica,1,2383,2.8,12237,2462281,73.4,7.4,2.527,0.0321,Medium-haul
800,RT00801,SCEL,OPLA,Chile,Pakistan,LatinAmerica,SouthAsia,1,200,0.2,5212,477659,95.2,6.7,2.502,0.2161,Short-haul
2204,RT02205,SKMR,VNPK,Colombia,Nepal,LatinAmerica,SouthAsia,1,752,0.9,757,137533,93.0,8.8,2.462,0.2297,Short-haul
2289,RT02290,HTKJ,KLAX,Tanzania,USA,Africa,NorthAmerica,1,1598,1.9,3074,471048,83.8,12.4,2.334,0.2098,Short-haul
4936,RT04937,UUEE,SCEL,Russia,Chile,Europe,LatinAmerica,1,4812,5.7,276,42167,86.1,12.1,2.272,0.1867,Medium-haul
4965,RT04966,HKMO,HTDA,Kenya,Tanzania,Africa,Africa,1,534,0.6,1111,161841,88.2,11.3,2.267,0.1928,Short-haul
329,RT00330,SAME,EDDH,Argentina,Germany,LatinAmerica,Europe,1,666,0.8,1374,262167,74.2,19.4,2.238,0.0843,Short-haul
580,RT00581,DNMM,OTHH,Nigeria,Qatar,Africa,MiddleEast,1,1013,1.2,2733,167335,83.7,3.5,2.192,0.2631,Short-haul
4636,RT04637,RKSS,VOBL,SouthKorea,India,AsiaPacific,AsiaPacific,1,625,0.7,4333,332350,86.3,10.9,2.158,0.1886,Short-haul
4621,RT04622,KDFW,KJFK,USA,USA,NorthAmerica,NorthAmerica,0,200,0.2,12427,1868500,76.6,13.1,2.132,0.2930,Short-haul
2829,RT02830,FNBG,WSSS,Angola,Singapore,Africa,SoutheastAsia,1,1026,1.2,100,10955,91.4,9.2,2.109,0.3578,Short-haul
537,RT00538,RPMD,WARR,Philippines,Indonesia,AsiaPacific,AsiaPacific,1,2340,2.8,186,23481,74.5,16.1,2.003,0.0794,Medium-haul
4423,RT04424,HEAT,FNBG,Egypt,Angola,Africa,Africa,1,2683,3.2,10969,1279984,87.2,11.5,1.942,0.1021,Medium-haul
3743,RT03744,MMUN,VVNB,Mexico,Vietnam,NorthAmerica,AsiaPacific,1,219,0.3,1791,235307,82.1,13.9,1.919,0.2432,Short-haul
4867,RT04868,YBBN,KDFW,Australia,USA,AsiaPacific,NorthAmerica,1,2740,3.2,3464,565967,82.7,15.1,1.896,0.1073,Medium-haul
1473,RT01474,KSFO,VVNB,USA,Vietnam,NorthAmerica,AsiaPacific,1,968,1.1,7189,1322651,75.4,8.6,1.870,0.0581,Short-haul

In [5]:
routes.sort_values(
    "risk_index",
    ascending=False
).head(20)

,route_id,departure_airport,arrival_airport,departure_country,arrival_country,departure_region,arrival_region,is_international,distance_km,avg_flight_time_h,annual_flights_2023,annual_passengers_2023,load_factor_pct,avg_aircraft_age_years,risk_index,incidents_per_mn_flights,route_type
886,RT00887,VVDN,VOMM,Vietnam,India,AsiaPacific,AsiaPacific,1,1936,2.3,5202,812464,91.3,10.4,2.854,0.5267,Short-haul
4974,RT04975,CYYC,KATL,Canada,USA,NorthAmerica,NorthAmerica,1,1942,2.3,6057,759882,84.7,11.0,2.851,0.1108,Short-haul
1683,RT01684,KORD,VNKT,USA,Nepal,NorthAmerica,SouthAsia,1,1039,1.2,917,107469,76.2,7.1,2.810,0.1219,Short-haul
966,RT00967,LFLL,FNHU,France,Angola,Europe,Africa,1,1105,1.3,6094,876915,79.1,15.2,2.546,0.3745,Short-haul
3414,RT03415,VIDP,SKCL,India,Colombia,AsiaPacific,LatinAmerica,1,2383,2.8,12237,2462281,73.4,7.4,2.527,0.0321,Medium-haul
800,RT00801,SCEL,OPLA,Chile,Pakistan,LatinAmerica,SouthAsia,1,200,0.2,5212,477659,95.2,6.7,2.502,0.2161,Short-haul
2204,RT02205,SKMR,VNPK,Colombia,Nepal,LatinAmerica,SouthAsia,1,752,0.9,757,137533,93.0,8.8,2.462,0.2297,Short-haul
2289,RT02290,HTKJ,KLAX,Tanzania,USA,Africa,NorthAmerica,1,1598,1.9,3074,471048,83.8,12.4,2.334,0.2098,Short-haul
4936,RT04937,UUEE,SCEL,Russia,Chile,Europe,LatinAmerica,1,4812,5.7,276,42167,86.1,12.1,2.272,0.1867,Medium-haul
4965,RT04966,HKMO,HTDA,Kenya,Tanzania,Africa,Africa,1,534,0.6,1111,161841,88.2,11.3,2.267,0.1928,Short-haul
329,RT00330,SAME,EDDH,Argentina,Germany,LatinAmerica,Europe,1,666,0.8,1374,262167,74.2,19.4,2.238,0.0843,Short-haul
580,RT00581,DNMM,OTHH,Nigeria,Qatar,Africa,MiddleEast,1,1013,1.2,2733,167335,83.7,3.5,2.192,0.2631,Short-haul
4636,RT04637,RKSS,VOBL,SouthKorea,India,AsiaPacific,AsiaPacific,1,625,0.7,4333,332350,86.3,10.9,2.158,0.1886,Short-haul
4621,RT04622,KDFW,KJFK,USA,USA,NorthAmerica,NorthAmerica,0,200,0.2,12427,1868500,76.6,13.1,2.132,0.2930,Short-haul
2829,RT02830,FNBG,WSSS,Angola,Singapore,Africa,SoutheastAsia,1,1026,1.2,100,10955,91.4,9.2,2.109,0.3578,Short-haul
537,RT00538,RPMD,WARR,Philippines,Indonesia,AsiaPacific,AsiaPacific,1,2340,2.8,186,23481,74.5,16.1,2.003,0.0794,Medium-haul
4423,RT04424,HEAT,FNBG,Egypt,Angola,Africa,Africa,1,2683,3.2,10969,1279984,87.2,11.5,1.942,0.1021,Medium-haul
3743,RT03744,MMUN,VVNB,Mexico,Vietnam,NorthAmerica,AsiaPacific,1,219,0.3,1791,235307,82.1,13.9,1.919,0.2432,Short-haul
4867,RT04868,YBBN,KDFW,Australia,USA,AsiaPacific,NorthAmerica,1,2740,3.2,3464,565967,82.7,15.1,1.896,0.1073,Medium-haul
1473,RT01474,KSFO,VVNB,USA,Vietnam,NorthAmerica,AsiaPacific,1,968,1.1,7189,1322651,75.4,8.6,1.870,0.0581,Short-haul

In [6]:
routes.sort_values(
    "distance_km",
    ascending=False
).head(20)

,route_id,departure_airport,arrival_airport,departure_country,arrival_country,departure_region,arrival_region,is_international,distance_km,avg_flight_time_h,annual_flights_2023,annual_passengers_2023,load_factor_pct,avg_aircraft_age_years,risk_index,incidents_per_mn_flights,route_type
4116,RT04117,VECC,SCEL,India,Chile,AsiaPacific,LatinAmerica,1,16000,18.8,1818,297021,76.0,1.0,0.148,0.0586,Long-haul
3067,RT03068,SCVD,CYYC,Chile,Canada,LatinAmerica,NorthAmerica,1,16000,18.8,3342,451571,72.5,6.2,0.119,0.1084,Long-haul
1263,RT01264,EDDB,VVTS,Germany,Vietnam,Europe,AsiaPacific,1,16000,18.8,6521,945781,83.2,4.9,0.110,0.2227,Long-haul
3327,RT03328,OERK,MMGL,Saudi Arabia,Mexico,MiddleEast,NorthAmerica,1,16000,18.8,975,97116,85.5,4.4,0.161,0.0342,Long-haul
856,RT00857,ZSPD,URSS,China,Russia,AsiaPacific,Europe,1,14627,17.2,15209,2395325,88.5,10.2,0.176,0.3104,Long-haul
1165,RT01166,ZUUU,EGGD,China,UK,AsiaPacific,Europe,1,14257,16.8,2094,261843,86.2,12.2,0.538,0.1800,Long-haul
4771,RT04772,MMMX,OICC,Mexico,Iran,NorthAmerica,MiddleEast,1,13719,16.1,373,55234,87.8,6.2,0.188,0.1541,Long-haul
862,RT00863,ZHHH,MMGL,China,Mexico,AsiaPacific,NorthAmerica,1,12407,14.6,1765,173248,83.2,19.0,0.123,0.0399,Long-haul
2003,RT02004,SBCF,WSSS,Brazil,Singapore,LatinAmerica,SoutheastAsia,1,12389,14.6,917,128444,74.5,16.6,0.259,0.1906,Long-haul
4992,RT04993,WARR,LFLL,Indonesia,France,AsiaPacific,Europe,1,12098,14.2,1138,201284,76.4,7.8,0.150,0.0781,Long-haul
4612,RT04613,LFPG,OPLA,France,Pakistan,Europe,SouthAsia,1,11933,14.0,2273,244732,97.2,11.1,0.694,0.2362,Long-haul
735,RT00736,OEJN,SAEZ,Saudi Arabia,Argentina,MiddleEast,LatinAmerica,1,11872,14.0,568,77793,73.4,7.8,0.427,0.1441,Long-haul
1136,RT01137,CYMX,MMMX,Canada,Mexico,NorthAmerica,NorthAmerica,1,11658,13.7,549,49799,92.9,5.7,0.460,0.1043,Long-haul
1327,RT01328,YMML,VTBS,Australia,Thailand,AsiaPacific,AsiaPacific,1,11575,13.6,3354,335794,75.9,12.0,0.356,0.2409,Long-haul
4609,RT04610,EGKK,LFPO,UK,France,Europe,Europe,1,11548,13.6,12207,1532952,73.3,11.4,0.261,0.0823,Long-haul
2898,RT02899,OPIS,SBCF,Pakistan,Brazil,SouthAsia,LatinAmerica,1,11405,13.4,1221,186235,86.5,5.2,0.100,0.1125,Long-haul
504,RT00505,MMGL,HTKA,Mexico,Tanzania,NorthAmerica,Africa,1,11398,13.4,2670,493046,92.6,11.6,0.141,0.3836,Long-haul
3815,RT03816,HAAB,OERK,Ethiopia,Saudi Arabia,Africa,MiddleEast,1,11087,13.0,1582,327912,86.1,13.7,0.299,0.1254,Long-haul
58,RT00059,YSSY,OEJN,Australia,Saudi Arabia,AsiaPacific,MiddleEast,1,10576,12.4,1443,195122,75.0,10.3,0.438,0.1010,Long-haul
2826,RT02827,WMKB,VIDP,Malaysia,India,AsiaPacific,AsiaPacific,1,10154,11.9,280,35464,91.3,8.8,1.332,0.0887,Long-haul